# Generated by Django 5.0 on 2023-12-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('average_score', models.IntegerField()),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estimation')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.object')),
            ],
        ),
    ]
