# Generated by Django 5.0 on 2023-12-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_estimation_student_estimation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='estimation_id',
            new_name='estimation',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='object_id',
            new_name='object',
        ),
    ]
